name: ProceduraPlugin
version: '${project.version}'
main: com.github.hhhzzzsss.proceduraplugin.ProceduraPlugin
api-version: 1.18
depend: [ FastAsyncWorldEdit ]
authors: [ hhhzzzsss ]
description: A plugin for making procedural structures in Minecraft
website: https://github.com/hhhzzzsss

commands:
  select:
    description: Select the region that you're currently standing in
    usage: /select
    permission: procedura.use
  deselect:
    description: Deselect region
    usage: /deselect
    permission: procedura.use
  register:
    description: Registers a new region
    usage: /register [<xyz dimensions>] [<bottom y>]
    permission: procedura.use
  unregister:
    description: Unregisters selected region
    usage: /unregister
    permission: procedura.use
  setname:
    description: Sets the name of the selected region
    usage: /setname [<name>]
    permission: procedura.use
  clearregion:
    description: Clears the selected region
    usage: /clearregion
    permission: procedura.use
  save:
    description: Saves the currently selected plot as a schematic
    usage: /save <filename>
    permission: procedura.use
  multisave:
    description: Saves the currently selected plot as a mutliple schematics
    usage: /save <filename> <pieces>
    permission: procedura.use
  goto:
    description: Teleports to a region
    usage: /goto [<region name>]
    permission: procedura.use
  setgeneratorpath:
    description: Sets the path to the generator programs folder (for auto running / zooming)
    usage: /setgeneratorpath <path>
    permission: procedura.use
  setprogram:
    description: Sets the specific generator program to use
    usage: /setprogram
    permission: procedura.use
  initposandzoom:
    description: Initializes the current position and zoom to send to the program
    usage: /initposandzoom <x> <y> <z> <zoom>
    permission: procedura.use
  zoom:
    description: Zooms by a factor
    usage: /zoom <factor>
    permission: procedura.use
  setcenter:
    description: Sets the center to your current position
    usage: /setcenter
    permission: procedura.use
  setcenterandzoom:
    description: Sets the center to your current position and zooms by the given factor
    usage: /setcenterandzoom <factor>
    permission: procedura.use
  shift:
    description: Shifts the pos to move the procedural build in the direction you're looking by a number of blocks
    usage: /shift <distance>
    permission: procedura.use
  run:
    description: Runs the chosen program with the current pos and zoom
    usage: /run
    permission: procedura.use
  getposandzoom:
    description: Displays the current pos and zoom
    usage: /getposandzoom
    permission: procedura.use
